# Generated by Django 4.1.7 on 2024-08-11 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('reservation_date', models.DateField(default=django.utils.timezone.now)),
                ('reservation_time', models.TimeField(default=django.utils.timezone.now)),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
